site_name: OptiPass Client

theme:
  name: "readthedocs"

extra:
  version: Version 1.0.5

extra_css:
  - css/tidegates.css
  
plugins:
  - search
  - mkdocstrings

nav:
  - "Home":
    - index.md
  - "Deployment":
    - deploy.md
  - "Documentation":
    - modules.md
    - gui.md
    - tests.md
